export enum PaymentMethod {
  QR_PROMPTPAY = 'QR_PROMPTPAY',
  CREDIT_CARD = 'CREDIT_CARD',
  K_PLUS = 'K_PLUS',
  SCB_EASY = 'SCB_EASY',
  KRUNGTHAI_NEXT = 'KRUNGTHAI_NEXT',
  BUALUANG = 'BUALUANG',
  KRUNGSRI = 'KRUNGSRI',
}
