name: Ping Supabase to Prevent Project Pausing

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * 1,4'  # Runs at 9:00 AM every Monday and Thursday

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install --save @supabase/supabase-js

      - name: Ping Supabase
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          node -e "
          (async () => {
            const { createClient } = require('@supabase/supabase-js');
            const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_KEY);
            try {
              const { data, error } = await supabase.from('keep_alive').select('id').limit(1);
              if (error) throw error;
              console.log('Supabase Response:', data);
            } catch (err) {
              console.error('Error:', err.message);
              process.exit(1);
            }
          })();
          "
